import React from 'react';
import {ColorValue, ViewStyle} from 'react-native';

export type IconType = React.FC<{
  fill?: ColorValue;
  style?: ViewStyle;
}>;

export * from './ArrowLeft/ArrowLeft';
export * from './ArrowRight/ArrowRight';
export * from './BackwardCircle/BackwardCircle';
export * from './Bell/Bell';
export * from './BellFill/BellFill';
export * from './Calendar/Calendar';
export * from './Camera/Camera';
export * from './Check/Check';
export * from './Checked/Checked';
export * from './ChevronLeft/ChevronLeft';
export * from './ChevronRight/ChevronRight';
export * from './Close/Close';
export * from './Command/Command';
export * from './Community/Community';
export * from './Delete/Delete';
export * from './Earth/Earth';
export * from './Ellipsis/Ellipsis';
export * from './Envelope/Envelope';
export * from './Explore/Explore';
export * from './ExploreFill/ExploreFill';
export * from './Facebook/Facebook';
export * from './FilmCamera/FilmCamera';
export * from './FilmCameraOff/FilmCameraOff';
export * from './ForwardCircle/ForwardCircle';
export * from './Friends/Friends';
export * from './HangUp/HangUp';
export * from './Heart/Heart';
export * from './Helplines/Helplines';
export * from './Home/Home';
export * from './HomeFill/HomeFill';
export * from './Info/Info';
export * from './Instagram/Instagram';
export * from './Journey/Journey';
export * from './JourneyFill/JourneyFill';
export * from './Languages/Languages';
export * from './Link/Link';
export * from './Logo/Logo';
export * from './Me/Me';
export * from './Megaphone/Megaphone';
export * from './Microphone/Microphone';
export * from './MicrophoneOff/MicrophoneOff';
export * from './Minus/Minus';
export * from './Pause/Pause';
export * from './Pencil/Pencil';
export * from './Play/Play';
export * from './Plus/Plus';
export * from './PrivateEye/PrivateEye';
export * from './Profile/Profile';
export * from './ProfileFill/ProfileFill';
export * from './Question/Question';
export * from './Report/Report';
export * from './Rewind/Rewind';
export * from './Safety/Safety';
export * from './Share/Share';
export * from './Slack/Slack';
export * from './Sparkles/Sparkles';
export * from './Star/Star';
export * from './StarFill/StarFill';
export * from './SunUp/SunUp';
export * from './SunUpFill/SunUpFill';
export * from './Wand/Wand';
