import React from 'react';
import {ColorValue} from 'react-native';

export type IconType = React.FC<{
  fill?: ColorValue;
}>;

export * from './ArrowLeft/ArrowLeft';
export * from './Back/Back';
export * from './BackwardCircle/BackwardCircle';
export * from './Bell/Bell';
export * from './Camera/Camera';
export * from './ChevronLeft/ChevronLeft';
export * from './ChevronRight/ChevronRight';
export * from './Close/Close';
export * from './Delete/Delete';
export * from './Ellipsis/Ellipsis';
export * from './FilmCamera/FilmCamera';
export * from './FilmCameraOff/FilmCameraOff';
export * from './Forward/Forward';
export * from './ForwardCircle/ForwardCircle';
export * from './HangUp/HangUp';
export * from './Home/Home';
export * from './HomeFill/HomeFill';
export * from './Info/Info';
export * from './Logo/Logo';
export * from './Microphone/Microphone';
export * from './MicrophoneOff/MicrophoneOff';
export * from './Minus/Minus';
export * from './Pause/Pause';
export * from './Play/Play';
export * from './Plus/Plus';
export * from './Private/Private';
export * from './Profile/Profile';
export * from './ProfileFill/ProfileFill';
export * from './Public/Public';
export * from './Rewind/Rewind';
export * from './Share/Share';
export * from './Calendar/Calendar';
export * from './Pencil/Pencil';
