export const SPACINGS = {
  ZERO: 0,
  FOUR: 4,
  EIGHT: 8,
  TWELVE: 12,
  SIXTEEN: 16,
  TWENTY: 20,
  TWENTYFOUR: 24,
  TWENTYEIGHT: 28,
  THIRTYTWO: 32,
  THIRTYSIX: 36,
  FOURTY: 40,
  FOURTYFOUR: 44,
  FOURTYEIGHT: 48,
  FIFTYTWO: 52,
  FIFTYSIX: 56,
  SIXTY: 60,
  NINTYSIX: 96,
};

export const GUTTERS = {SMALL: SPACINGS.SIXTEEN, BIG: SPACINGS.THIRTYTWO};
