# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :logBuildPath do |params|
  UI.message('')
  UI.header('Build output path')
  UI.message(params[:path])
  UI.message('')
end

platform :ios do
  build_path = './build/ios'

  desc 'Build an adhoc version to build dir'
  lane :adhoc do

    # Get latest adhoc provisioning profile
    match(
      app_identifier: ENV['IOS_BUNDLE_IDENTIFIER'], 
      type: 'adhoc', 
      readonly: true
    )

    build_ios_app(
      workspace: './ios/twentyninek.xcworkspace', 
      scheme: ENV['IOS_SCHEME'],
      export_method: 'ad-hoc',
      output_directory: build_path
    )

    logBuildPath(path: build_path)
  end

  desc 'Build and publish a new version to TestFlight'
  lane :beta do
    # Get latest appstore provisioning profile
    match(
      app_identifier: ENV['IOS_BUNDLE_IDENTIFIER'], 
      type: 'appstore', 
      readonly: true
    )

    increment_build_number(xcodeproj: './ios/twentyninek.xcodeproj')

    build_ios_app(
      workspace: './ios/twentyninek.xcworkspace', 
      scheme: ENV['IOS_SCHEME'],
      export_method: 'app-store',
    )

    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end