# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :logBuildPath do |params|
  UI.message('')
  UI.header('Build output path')
  UI.message(params[:path])
  UI.message('')
end

platform :ios do
  build_path = './build/ios'

  desc 'Build and publish a new version to TestFlight'
  lane :app do
    # Get latest appstore provisioning profile
    match(
      app_identifier: ENV['IOS_BUNDLE_IDENTIFIER'],
      type: 'appstore',
      readonly: true
    )

    increment_build_number(xcodeproj: './ios/twentyninek.xcodeproj')

    build_ios_app(
      workspace: './ios/twentyninek.xcworkspace',
      scheme: ENV['IOS_SCHEME'],
      export_method: 'app-store',
    )

    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end

platform :android do
  build_path = './build/android'

  desc 'Build and publish a new version to Google Play Store'
  lane :app do
    increment_version_code(
      gradle_file_path: './android/app/build.gradle'
    )

    build_android_app(
      task: 'clean bundle',
      flavor: ENV['ANDROID_FLAVOR'],
      build_type: 'Release',
      project_dir: './android',
      properties: {
        "UPLOAD_STORE_FILE" => "release.keystore",
        "UPLOAD_KEY_ALIAS" => "release",
        "UPLOAD_STORE_PASSWORD" => ENV['ANDROID_UPLOAD_STORE_PASSWORD'],
        "UPLOAD_KEY_PASSWORD" => ENV['ANDROID_UPLOAD_KEY_PASSWORD'],
      }
    )

    upload_to_play_store(
      track: 'internal',
      release_status: 'draft',
      package_name: ENV['ANDROID_PACKAGE_NAME'],
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end
